/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    // invoking method on a possibly null value
    public boolean getGreeting() {
        return Util.getNullableValue().equals(Boolean.FALSE);
    }

    // auto-unboxing a possibly null value
    public boolean getValue() {
        return Util.getNullableValue();
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
